# nom du workflow
name: Foodtruck CI workflow

# déclencheur du workflow
on:
  push:
    branches: [ master ]

# tâches
jobs:
  # nom de la tâche
  CI:
    # choix de l'OS
    runs-on: ubuntu-latest
    
    # étapes de la tâche
    steps:
      -
        name: Cloner le repository
        uses: actions/checkout@v6

      -
        name: Installer les dépendances
        working-directory: code
        run: npm ci

      -
        name: Compiler le projet React
        working-directory: code
        run: npm run build

      -
        name: Démarrer MySQL et importer la base de données de tests
        working-directory: code/mysql
        run: |
          sudo service mysql start
          mysql -uroot -proot -e "source foodtruck.test.sql;"
          mysql -uroot -proot -e "source ia.test.sql;"
          mysql -uroot -proot -e "show databases;"

      -
        name: Exécuter les tests
        working-directory: code
        run: npm run test